name: bd14-despliegue-IA3
channels: 
  - defaults 
  - conda-forge 
dependencies: 
  - ipykernel
  - pip  
  - python=3.11.0
  - setuptools 
  - wheel 
  - poppler 
  - pip: 
    - fastapi==0.115.6
    - mlflow==2.18.0
    - uvicorn==0.23.2